# Generated by Django 3.1.1 on 2020-10-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alllisting_bid_closebid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Closebid',
            new_name='Closedbid',
        ),
    ]
